version: "3.3"
services:
  mysqldatabase:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'msc_database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    container_name: mysqldatabase
    networks:
      - msc-network
  msc-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: jsuryadharma/msc-backend:latest
    depends_on:
      - mysqldatabase
    ports:
      - '8080:8080'
    expose:
      - '8080'
    container_name: msc-backend
    networks:
      - msc-network
  msc-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: jsuryadharma/msc-frontend:latest
    container_name: msc-frontend
    depends_on:
      - msc-backend
    ports:
      - "3000:80"
    networks:
      - msc-network