version: "3.3"
services:
  msc-backend:
    image: jsuryadharma/msc-backend:latest
    depends_on:
      - mysqldatabase
    ports:
      - '8080:8080'
    expose:
      - '8080'
    container_name: msc-backend
    networks:
      - msc-network
  msc-frontend:
    image: jsuryadharma/msc-frontend:latest
    container_name: msc-frontend
    depends_on:
      - msc-backend
    ports:
      - "3000:80"
    networks:
      - msc-network