version: '3.3'

services:
  mysqldatabase:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'msc_database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    container_name: mysqldatabase
    networks:
      - msc-network
  jenkins-service:
    image: jenkins-docker
    ports:
      - '8070:8080'
    expose:
      - '8070'
    container_name: jenkins-service
    volumes:
      - C:/Users/jsury/OneDrive/Desktop/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - msc-network
networks:
  msc-network:
    driver: bridge