version: "3.3"
services:
  msc-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: jsuryadharma/msc-backend:latest
    ports:
      - '8080:8080'
    expose:
      - '8080'
    container_name: msc-backend
    networks:
      - default
  msc-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: jsuryadharma/msc-frontend:latest
    container_name: msc-frontend
    depends_on:
      - msc-backend
    ports:
      - "3000:80"
    networks:
      - default
networks:
  default:
    external:
      name: msc-network