FROM node:16 AS build
WORKDIR /app
COPY ./msc-frontend/package.json .
RUN npm config set proxy http://U072467:Jsuryad1@kpproxygsit:8080
RUN npm install --force
COPY ./msc-frontend/ .
RUN npm run build

FROM nginx:latest
COPY --from=build /app/build/ /usr/share/nginx/html
