CREATE TABLE FormAuthor (
    formAuthorId VARCHAR(100) NOT NULL,
    formId VARCHAR(100) NOT NULL,
    userId VARCHAR(100) NOT NULL,
    inviteDate BIGINT NOT NULL,
    CONSTRAINT formAuthorPK PRIMARY KEY (formAuthorId),
    CONSTRAINT formAuthorFK FOREIGN KEY (formId) REFERENCES Form (formId)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT formAuthorFK2 FOREIGN KEY (userId) REFERENCES User (userId)
        ON UPDATE CASCADE ON DELETE CASCADE
)