CREATE TABLE FormAuthor (
    formAuthorId VARCHAR(100) PRIMARY KEY,
    formId VARCHAR(100) NOT NULL REFERENCES Form(formId) ON UPDATE CASCADE ON DELETE CASCADE,
    userId VARCHAR(100) NOT NULL REFERENCES User(userId) ON UPDATE CASCADE ON DELETE CASCADE
)