CREATE TABLE FormLastEdited (
    lastEditedId VARCHAR(100) NOT NULL,
    formId VARCHAR(100) NOT NULL,
    userId VARCHAR(100) NOT NULL,
    modifyDate BIGINT NOT NULL,
    CONSTRAINT formLastEditedPK PRIMARY KEY (lastEditedId),
    CONSTRAINT formLastEditedFK FOREIGN KEY (formId) REFERENCES Form (formId)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT formLastEditedFK2 FOREIGN KEY (userId) REFERENCES User (userId)
        ON UPDATE CASCADE ON DELETE CASCADE
)