spring:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://mysqldatabase:3306/msc_database
      username: user
      password: password
      pool-size: 30
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.jdbc.lob.non_contextual_creation: true
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
    multipart:
      max-file-size: 2MB
  servlet:
    multipart:
      max-request-size: 2MB