spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://mysqldatabase:3306/msc_database
    username: user
    password: password
    pool-size: 30
  jpa:
    generate-ddl: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB